embeddings:
  glove: '/usr/src/app/data/embedding/glove.6B.50d_normalized.txt'

paths:
  annotations: '/usr/src/app/data/input/TrainVal/annotations'
  train_images: '/usr/src/app/data/input/TrainVal/train2014'
  val_images: '/usr/src/app/data/input/TrainVal/val2014'
  test_metadata: '/usr/src/app/data/input'
  test_images: '/usr/src/app/data/input'
  logs: '/usr/src/app/data/logs'
  models: '/usr/src/app/data/models'

image_dimensions: [224, 224, 3]

word_embedding_size: 50

dictionary_size: 14831

max_caption_length: 15

stop_word: '.'

spice:
  # relative to spice.py
  cache_dir: 'cache'
  tmp_dir: 'tmp'