embeddings:
  glove: '/dl_data/glove/glove_small.txt'

paths:
  annotations: '/dl_data/TrainVal/annotations'
  train_images: '/dl_data/TrainVal/train2014'
  val_images: '/dl_data/TrainVal/val2014'
  test_metadata: '/dl_data/Evaluation-I'
  test_images: '/dl_data/Evaluation-I/eval-I'
  logs: '/dl_data/logs'
  models: '/dl_data/models'

image_dimensions: [224, 224, 3]

word_embedding_size: 50

max_caption_length: 15

stop_word: '.'

spice:
  # relative to spice.py
  cache_dir: 'cache'
  tmp_dir: 'tmp'